FROM python:2.7
MAINTAINER Aina Martinez Zurita <amartine@broadinstitute.org>

ENV TERM=xterm-256color

#Intstall python dependencies
RUN pip install scipy

#Copy the github repo
RUN git clone https://github.com/broadinstitute/broad-fungalgroup.git
